[package]
name = "fdfzf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.2"
dirs = "5.0.1"
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.10"
